POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Category 2",
  "description": "Category1 description"
}

###

GET http://localhost:8080/category/d91f1321-a1a9-4d21-b5fe-33c0766000ac
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json


###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product1 description",
  "price": 100,
  "image_url": "https://github.com",
  "category_id": "7ffc4c8b-b534-43ad-9959-a3098ed17aa6",
}

###